matrix:
  include:
    - language: python
      python: 2.7
      before_script:
        - cd python
      script:
        - python pythontest

    - language: java
      before_script:
        - cd java
      script:
        - mvn clean 