matrix:
  include:
    - language: python
      python: 2.7
      before_script:
        - cd python
      script:
        - python pythontest.py

    - language: java
      before_script:  
        - cd java
      sudo: false
      script: mvn clean verify